VERSION 0.6
FROM node:18-alpine
USER node
WORKDIR /home/node/app

build:
  COPY package*.json ./
  RUN npm install
  COPY tsconfig*.json ./
  COPY build.cjs ./
  COPY src/ src/
  RUN npm run check && npm run build
  SAVE ARTIFACT dist AS LOCAL dist
  SAVE ARTIFACT dist/index.cjs generate-metalink AS LOCAL generate-metalink
