VERSION 0.6

ingress-caddy:
  FROM caddy:2-alpine
  RUN \
    apk --no-cache add libcap && \
    setcap cap_net_bind_service=+ep /usr/bin/caddy && \
    apk del libcap
  RUN \
    addgroup -g 10443 -S caddy && \
    adduser -u 10443 -h / -G caddy -S caddy
  USER caddy

  VOLUME /config
  VOLUME /data

  SAVE IMAGE ingress-caddy:local
